### ISSUE TITLE
fpm is not added correctly to PATH for MSYS2

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/setup-fpm#4]
Using setup-fpm together with setup-msys2 currently does not add fpm correctly to the PATH.

Sample workflow to reproduce:

```yml
jobs:
  msys2-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MinGW native environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          git
          mingw-w64-x86_64-gcc-fortran

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        fpm-version: 'v0.1.3'

    - run: fpm --version
```

**Comment by LKedward** [comment]
Thanks for reporting. A 'quick-and-dirty' solution could be to use [`path-type`](https://github.com/msys2/setup-msys2#path-type)=`inherit` for the `setup-msys2` action. However I believe it isn't preferable to inherit the full system path when using the MSYS2 environment.

Currently the temporary download folder for the *fpm* binary is added to the path, however, as you show, this doesn't propagate to MSYS2 for the default `path-type=minimal` configuration and more importantly could lead to unexpected side-effects if other executables end up in the same temporary directory.

A solution could therefore be to have the action move the *fpm* binary to a suitable place already on the path. On Windows this could then be a location that is inherited by MSYS2 for the default `path-type=minimal` configuration — though I'm not sure where on Windows would be to put it?.

**Comment by awvwgk** [comment]
I guess the correct way to use fpm with setup-msys2 would be (not working yet of course)
```yml
    - name: Setup MinGW native environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          git
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-fpm
```
Something to consider for the future once we start packaging fpm for different package managers.
